# Generated by Django 4.1.7 on 2023-06-30 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springeval', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultentry',
            name='code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Link to code'),
        ),
        migrations.AlterField(
            model_name='springuser',
            name='description',
            field=models.TextField(help_text='Please provide a brief justification of why you need access to the benchmark.', max_length=1000, verbose_name='Description*'),
        ),
        migrations.AlterField(
            model_name='springuser',
            name='email',
            field=models.EmailField(help_text='Please use your university/organisation mail address.', max_length=255, unique=True, verbose_name='email address*'),
        ),
        migrations.AlterField(
            model_name='springuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='springuser',
            name='university',
            field=models.CharField(max_length=100, verbose_name='University/Organization*'),
        ),
        migrations.AlterField(
            model_name='springuser',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='Personal website'),
        ),
    ]
