# Generated by Django 5.1.5 on 2025-03-13 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "springeval",
            "0002_resultentry_code_url_alter_springuser_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="resultentry",
            name="robust_1px_D1_total",
            field=models.FloatField(default=-1, verbose_name="robust 1px D1 total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_1px_Fl_total",
            field=models.FloatField(default=-1, verbose_name="robust 1px Fl total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_Abs_D1_total",
            field=models.FloatField(default=-1, verbose_name="robust Abs D1 total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_D1_total",
            field=models.FloatField(default=-1, verbose_name="robust D1 total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_EPE_Fl_total",
            field=models.FloatField(default=-1, verbose_name="robust EPE Fl total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_Fl_total",
            field=models.FloatField(default=-1, verbose_name="robust Fl total"),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp1_1px_total",
            field=models.FloatField(
                default=-1, verbose_name="robust 1px D1 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp1_Abs_total",
            field=models.FloatField(
                default=-1, verbose_name="robust Abs D1 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp1_D1_total",
            field=models.FloatField(
                default=-1, verbose_name="robust D1 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp2_1px_total",
            field=models.FloatField(
                default=-1, verbose_name="robust 1px D2 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp2_Abs_total",
            field=models.FloatField(
                default=-1, verbose_name="robust Abs D2 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_disp2_D2_total",
            field=models.FloatField(
                default=-1, verbose_name="robust D2 total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_flow_1px_total",
            field=models.FloatField(
                default=-1, verbose_name="robust 1px Fl total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_flow_EPE_total",
            field=models.FloatField(
                default=-1, verbose_name="robust EPE Fl total (scene flow)"
            ),
        ),
        migrations.AddField(
            model_name="resultentry",
            name="robust_flow_Fl_total",
            field=models.FloatField(
                default=-1, verbose_name="robust Fl total (scene flow)"
            ),
        ),
    ]
