# Generated by Django 5.1.5 on 2025-03-19 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("springeval", "0003_resultentry_robust_1px_d1_total_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RobustCorruptionResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "corruption_name",
                    models.CharField(
                        choices=[
                            ("brightness", "Brightness"),
                            ("contrast", "Contrast"),
                            ("saturate", "Saturate"),
                            ("defocus_blur", "Defocus Blur"),
                            ("gaussian_blur", "Gaussian Blur"),
                            ("glass_blur", "Glass Blur"),
                            ("motion_blur", "Motion Blur"),
                            ("zoom_blur", "Zoom Blur"),
                            ("gaussian_noise", "Gaussian Noise"),
                            ("impulse_noise", "Impulse Noise"),
                            ("speckle_noise", "Speckle Noise"),
                            ("shot_noise", "Shot Noise"),
                            ("pixelate", "Pixelate"),
                            ("jpeg_compression", "JPEG Compression"),
                            ("elastic_transform", "Elastic Transform"),
                            ("fog", "Fog"),
                            ("frost", "Frost"),
                            ("rain", "Rain"),
                            ("snow", "Snow"),
                            ("spatter", "Spatter"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "robust_1px_D1",
                    models.FloatField(default=-1, verbose_name="robust 1px D1"),
                ),
                (
                    "robust_Abs_D1",
                    models.FloatField(default=-1, verbose_name="robust Abs D1"),
                ),
                ("robust_D1", models.FloatField(default=-1, verbose_name="robust D1")),
                (
                    "robust_EPE_Fl",
                    models.FloatField(default=-1, verbose_name="robust EPE Fl"),
                ),
                ("robust_Fl", models.FloatField(default=-1, verbose_name="robust Fl")),
                (
                    "robust_1px_Fl",
                    models.FloatField(default=-1, verbose_name="robust 1px Fl"),
                ),
                (
                    "robust_disp1_1px",
                    models.FloatField(
                        default=-1, verbose_name="robust 1px D1 total (scene flow)"
                    ),
                ),
                (
                    "robust_disp1_Abs",
                    models.FloatField(
                        default=-1, verbose_name="robust Abs D1 total (scene flow)"
                    ),
                ),
                (
                    "robust_disp1_D1",
                    models.FloatField(
                        default=-1, verbose_name="robust D1 total (scene flow)"
                    ),
                ),
                (
                    "robust_disp2_1px",
                    models.FloatField(
                        default=-1, verbose_name="robust 1px D2 total (scene flow)"
                    ),
                ),
                (
                    "robust_disp2_Abs",
                    models.FloatField(
                        default=-1, verbose_name="robust Abs D2 total (scene flow)"
                    ),
                ),
                (
                    "robust_disp2_D2",
                    models.FloatField(
                        default=-1, verbose_name="robust D2 total (scene flow)"
                    ),
                ),
                (
                    "robust_flow_EPE",
                    models.FloatField(
                        default=-1, verbose_name="robust EPE Fl total (scene flow)"
                    ),
                ),
                (
                    "robust_flow_Fl",
                    models.FloatField(
                        default=-1, verbose_name="robust Fl total (scene flow)"
                    ),
                ),
                (
                    "robust_flow_1px",
                    models.FloatField(
                        default=-1, verbose_name="robust 1px Fl total (scene flow)"
                    ),
                ),
                (
                    "result_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="robust_corruption_results",
                        to="springeval.resultentry",
                    ),
                ),
            ],
        ),
    ]
