# Generated by Django 5.1.5 on 2025-03-19 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("springeval", "0004_robustcorruptionresult"),
    ]

    operations = [
        migrations.AddField(
            model_name="resultentry",
            name="evaluate_robustness",
            field=models.BooleanField(default=False),
        ),
    ]
