# Generated by Django 5.1.5 on 2025-03-19 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("springeval", "0005_resultentry_evaluate_robustness"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resultentry",
            name="evaluate_robustness",
            field=models.BooleanField(default=True),
        ),
    ]
