# Generated by Django 5.2.1 on 2025-05-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('springeval', '0006_alter_resultentry_evaluate_robustness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultentry',
            name='evaluate_robustness',
            field=models.BooleanField(default=False),
        ),
    ]
